version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "langchain"
      - dependency-name: "langchain-core"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
